// Muse tools stripper — CLIProxyAPI request interceptor + normalizer.
//
// Problem: codex clients (0.15x) send {"type":"additional_tools", ...} as
// input[0] (exec sandbox tool declarations). The opencode zen free tier
// (muse-spark-1.3-contributor-free, alias muse-free / muse) does not accept
// this type and rejects the whole request with:
//
//	400 [invalid_request_error] `input[0]` did not match any supported type
//
// Verified live: same payload without the additional_tools entry returns 200.
//
// Fix: for zen free-tier models only, drop input[] entries whose type is
// additional_tools. Two hooks cover both request shapes:
//   - request.intercept_before/after: strips when the client payload already
//     carries input[] (translation has nothing to generate yet).
//   - request.normalize: strips after native translation, covering requests
//     whose input[] is only generated by the provider translator.
//
// Standard entries (message / function_call / function_call_output /
// reasoning / custom tool calls) pass through untouched. exec sandbox is
// unavailable behind this filter; conversation, file edits and shell calls
// are unaffected.
package main

/*
#include <stdint.h>
#include <stdlib.h>

typedef struct {
	void* ptr;
	size_t len;
} cliproxy_buffer;

typedef int (*cliproxy_host_call_fn)(void*, const char*, const uint8_t*, size_t, cliproxy_buffer*);
typedef void (*cliproxy_host_free_fn)(void*, size_t);

typedef struct {
	uint32_t abi_version;
	void* host_ctx;
	cliproxy_host_call_fn call;
	cliproxy_host_free_fn free_buffer;
} cliproxy_host_api;

typedef int (*cliproxy_plugin_call_fn)(char*, uint8_t*, size_t, cliproxy_buffer*);
typedef void (*cliproxy_plugin_free_fn)(void*, size_t);
typedef void (*cliproxy_plugin_shutdown_fn)(void);

typedef struct {
	uint32_t abi_version;
	cliproxy_plugin_call_fn call;
	cliproxy_plugin_free_fn free_buffer;
	cliproxy_plugin_shutdown_fn shutdown;
} cliproxy_plugin_api;

extern int cliproxyPluginCall(char*, uint8_t*, size_t, cliproxy_buffer*);
extern void cliproxyPluginFree(void*, size_t);
extern void cliproxyPluginShutdown(void);

static const cliproxy_host_api* stored_host;

static void store_host_api(const cliproxy_host_api* host) {
	stored_host = host;
}
*/
import "C"

import (
	"encoding/json"
	"strings"
	"unsafe"

	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

const (
	abiVersion        uint32 = 1
	pluginID                 = "muse-tools-stripper"
	maxCGoBytesLength uint64 = 1<<31 - 1
)

var pluginVersion = "0.1.3"

// zenFreeModels matches the opencode zen free-tier models behind the
// muse-free / muse aliases. Matching is case-insensitive and ignores any
// provider prefix; the interceptors check both RequestedModel (client
// alias) and Model (upstream id). The normalizer can only check Model:
// RequestTransformRequest carries no RequestedModel field.
// NOTE: paid builds (muse-spark-1.3-contributor, muse-spark-contributor)
// are deliberately ABSENT: they may support additional_tools, and must
// never be filtered without evidence.
var zenFreeModels = map[string]struct{}{
	"muse-free":                       {},
	"muse":                            {},
	"muse-spark-free":                 {},
	"muse-spark-1.3-contributor-free": {},
	"muse-spark-contributor-free":     {},
}

// strippedTypes are input[] entry types the zen free tier rejects.
var strippedTypes = map[string]struct{}{
	"additional_tools": {},
}

type envelope struct {
	OK     bool            `json:"ok"`
	Result json.RawMessage `json:"result,omitempty"`
	Error  *envelopeError  `json:"error,omitempty"`
}

type envelopeError struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

type registration struct {
	SchemaVersion uint32       `json:"schema_version"`
	Metadata      metadata     `json:"metadata"`
	Capabilities  capabilities `json:"capabilities"`
}

type metadata struct {
	Name             string `json:"Name"`
	Version          string `json:"Version"`
	Author           string `json:"Author"`
	GitHubRepository string `json:"GitHubRepository"`
	Logo             string `json:"Logo"`
	ConfigFields     []any  `json:"ConfigFields"`
}

type capabilities struct {
	RequestInterceptor bool `json:"request_interceptor"`
	RequestNormalizer  bool `json:"request_normalizer"`
}

// interceptRequest mirrors pluginapi.RequestInterceptRequest (only the
// fields we read).
type interceptRequest struct {
	SourceFormat   string              `json:"SourceFormat"`
	ToFormat       string              `json:"ToFormat"`
	Model          string              `json:"Model"`
	RequestedModel string              `json:"RequestedModel"`
	Stream         bool                `json:"Stream"`
	Headers        map[string][]string `json:"Headers"`
	Body           []byte              `json:"Body"`
}

// interceptResponse mirrors pluginapi.RequestInterceptResponse: Body
// non-empty replaces the request payload.
type interceptResponse struct {
	Body []byte `json:"Body"`
}

// normalizeRequest mirrors pluginapi.RequestTransformRequest (only the
// fields we read). The normalizer runs after native translation, so Body
// is the provider payload and Model is the resolved model identifier.
type normalizeRequest struct {
	FromFormat string `json:"FromFormat"`
	ToFormat   string `json:"ToFormat"`
	Model      string `json:"Model"`
	Stream     bool   `json:"Stream"`
	Body       []byte `json:"Body"`
}

// normalizeResponse mirrors pluginapi.PayloadResponse: Body non-empty
// replaces the translated payload.
type normalizeResponse struct {
	Body []byte `json:"Body"`
}

func main() {}

//export cliproxy_plugin_init
func cliproxy_plugin_init(host *C.cliproxy_host_api, plugin *C.cliproxy_plugin_api) C.int {
	if plugin == nil {
		return 1
	}
	C.store_host_api(host)
	plugin.abi_version = C.uint32_t(abiVersion)
	plugin.call = C.cliproxy_plugin_call_fn(C.cliproxyPluginCall)
	plugin.free_buffer = C.cliproxy_plugin_free_fn(C.cliproxyPluginFree)
	plugin.shutdown = C.cliproxy_plugin_shutdown_fn(C.cliproxyPluginShutdown)
	return 0
}

//export cliproxyPluginCall
func cliproxyPluginCall(method *C.char, request *C.uint8_t, requestLen C.size_t, response *C.cliproxy_buffer) (status C.int) {
	status = 1
	if response != nil {
		response.ptr = nil
		response.len = 0
	}
	defer func() {
		if recover() != nil {
			writeResponse(response, errorEnvelope("plugin_panic", "plugin call failed"))
			status = 1
		}
	}()
	if method == nil {
		writeResponse(response, errorEnvelope("invalid_method", "method is required"))
		return 1
	}
	if !requestLengthSupported(uint64(requestLen)) {
		writeResponse(response, errorEnvelope("request_too_large", "request exceeds plugin ABI limit"))
		return 1
	}
	var payload []byte
	if requestLen > 0 {
		if request == nil {
			writeResponse(response, errorEnvelope("invalid_request", "request buffer is required"))
			return 1
		}
		payload = C.GoBytes(unsafe.Pointer(request), C.int(requestLen))
	}
	raw, callStatus := processPluginCall(C.GoString(method), payload)
	writeResponse(response, raw)
	return C.int(callStatus)
}

func requestLengthSupported(length uint64) bool {
	return length <= maxCGoBytesLength
}

func processPluginCall(method string, payload []byte) ([]byte, int) {
	raw, errHandle := handleMethod(method, payload)
	if errHandle != nil {
		return errorEnvelope("plugin_error", errHandle.Error()), 1
	}
	return raw, 0
}

//export cliproxyPluginFree
func cliproxyPluginFree(ptr unsafe.Pointer, len C.size_t) {
	if ptr != nil {
		C.free(ptr)
	}
	_ = len
}

//export cliproxyPluginShutdown
func cliproxyPluginShutdown() {}

func handleMethod(method string, payload []byte) ([]byte, error) {
	switch method {
	case "plugin.register", "plugin.reconfigure":
		return okEnvelopeJSON(registration{
			SchemaVersion: abiVersion,
			Metadata: metadata{
				Name:             pluginID,
				Version:          pluginVersion,
				Author:           "ahoo",
				GitHubRepository: "https://github.com/ahoo/cpa-plugin-muse-tools-stripper",
				Logo:             "",
				ConfigFields:     []any{},
			},
			Capabilities: capabilities{RequestInterceptor: true, RequestNormalizer: true},
		})
	case "request.intercept_before", "request.intercept_after":
		return intercept(payload)
	case "request.normalize":
		return normalize(payload)
	default:
		// Never fail a request on unknown probes.
		return okEnvelopeJSON(interceptResponse{})
	}
}

func intercept(payload []byte) ([]byte, error) {
	var req interceptRequest
	if len(payload) > 0 {
		if errDecode := json.Unmarshal(payload, &req); errDecode != nil {
			return nil, errDecode
		}
	}
	if len(req.Body) == 0 {
		return okEnvelopeJSON(interceptResponse{})
	}
	// additional_tools/input[] is a codex-protocol shape; only skip when
	// both formats are known and neither is codex. ToFormat is empty
	// before credential selection (before-auth), so an empty value must
	// not block: fail open toward stripping, the input[] check below is
	// the real guard.
	if isKnownNonCodexFormat(req.SourceFormat) && isKnownNonCodexFormat(req.ToFormat) {
		return okEnvelopeJSON(interceptResponse{})
	}
	if !isZenFree(req.RequestedModel) && !isZenFree(req.Model) {
		return okEnvelopeJSON(interceptResponse{})
	}
	fixed, changed := stripUnsupportedInput(req.Body)
	if !changed {
		return okEnvelopeJSON(interceptResponse{})
	}
	return okEnvelopeJSON(interceptResponse{Body: fixed})
}

// normalize handles request.normalize, which core invokes after native
// translation. Requests whose input[] is only generated by the provider
// translator are invisible to the interceptors above; this covers them.
// Only strips when the translated payload targets the codex format and the
// resolved model is a zen free-tier model.
func normalize(payload []byte) ([]byte, error) {
	var req normalizeRequest
	if len(payload) > 0 {
		if errDecode := json.Unmarshal(payload, &req); errDecode != nil {
			return nil, errDecode
		}
	}
	if len(req.Body) == 0 {
		return okEnvelopeJSON(normalizeResponse{Body: req.Body})
	}
	// additional_tools/input[] is a codex-protocol shape; never touch
	// payloads translated toward other formats.
	if !strings.EqualFold(strings.TrimSpace(req.ToFormat), "codex") {
		return okEnvelopeJSON(normalizeResponse{Body: req.Body})
	}
	if !isZenFree(req.Model) {
		return okEnvelopeJSON(normalizeResponse{Body: req.Body})
	}
	fixed, changed := stripUnsupportedInput(req.Body)
	if !changed {
		return okEnvelopeJSON(normalizeResponse{Body: req.Body})
	}
	return okEnvelopeJSON(normalizeResponse{Body: fixed})
}

// isKnownNonCodexFormat reports whether a format value is present and is
// definitely not the codex protocol. Empty means "unknown" (e.g. ToFormat
// before credential selection) and must not block stripping.
func isKnownNonCodexFormat(format string) bool {
	f := strings.TrimSpace(format)
	return f != "" && !strings.EqualFold(f, "codex")
}

// stripThinkingSuffix mirrors core thinking.ParseSuffix: the last "("
// through a trailing ")" is a thinking suffix (e.g. "muse-free(high)"
// -> "muse-free"). Only stripped when the string ends with ")".
// Like the router's base-model extraction, any trailing parenthesized
// segment is treated as a suffix without validating its content.
func stripThinkingSuffix(m string) string {
	lastOpen := strings.LastIndex(m, "(")
	if lastOpen == -1 {
		return m
	}
	if !strings.HasSuffix(m, ")") {
		return m
	}
	return strings.TrimSpace(m[:lastOpen])
}

func isZenFree(model string) bool {
	// Strip the thinking suffix first (core parses suffix before routing),
	// then the provider prefix, then once more in case the suffix itself
	// carried a separator.
	m := stripThinkingSuffix(strings.ToLower(strings.TrimSpace(model)))
	if i := strings.LastIndex(m, "/"); i >= 0 {
		m = m[i+1:]
	}
	m = stripThinkingSuffix(strings.TrimSpace(m))
	if m == "" {
		return false
	}
	if _, ok := zenFreeModels[m]; ok {
		return true
	}
	// Suffix-tolerant for future free variants (muse-spark-1.4-...-free),
	// but never match the paid contributor builds without a free marker:
	// "muse-spark-1.3-contributor" must stay untouched.
	if !strings.HasSuffix(m, "free") {
		return false
	}
	return strings.HasPrefix(m, "muse")
}

// stripUnsupportedInput removes input[] entries with rejected types.
// Returns the rewritten body and whether anything changed.
func stripUnsupportedInput(body []byte) ([]byte, bool) {
	if !gjson.ValidBytes(body) {
		return body, false
	}
	input := gjson.GetBytes(body, "input")
	if !input.IsArray() {
		return body, false
	}
	keep := make([]json.RawMessage, 0, len(input.Array()))
	changed := false
	for _, item := range input.Array() {
		t := strings.ToLower(strings.TrimSpace(item.Get("type").String()))
		if _, drop := strippedTypes[t]; drop {
			changed = true
			continue
		}
		keep = append(keep, json.RawMessage(item.Raw))
	}
	if !changed {
		return body, false
	}
	raw, err := json.Marshal(keep)
	if err != nil {
		return body, false
	}
	out, err := sjson.SetRawBytes(body, "input", raw)
	if err != nil {
		return body, false
	}
	return out, true
}

func okEnvelopeJSON(result any) ([]byte, error) {
	raw, errMarshal := json.Marshal(result)
	if errMarshal != nil {
		return nil, errMarshal
	}
	return json.Marshal(envelope{OK: true, Result: json.RawMessage(raw)})
}

func errorEnvelope(code, message string) []byte {
	raw, _ := json.Marshal(envelope{OK: false, Error: &envelopeError{Code: code, Message: message}})
	return raw
}

func writeResponse(response *C.cliproxy_buffer, raw []byte) {
	if response == nil || len(raw) == 0 {
		return
	}
	ptr := C.CBytes(raw)
	if ptr == nil {
		return
	}
	response.ptr = ptr
	response.len = C.size_t(len(raw))
}
